# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7066f58a1009422dd53b36ff17409831a1c66d93d0a581c681d3c46c6c26082be60f899be42573a7177f9ad54573665352a0f7498afbbac29e56791b324e1be4

test:
  secret_key_base: 474be17919531ce17a394061d6274e7c22f0d231ee6f168dcc305e1134f346b9dda395bee319ee6af8a3df5efd699cad023a7e076969ef1836778baafdeed2e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  action_gun_key: 'key-58f9a358ddb5394fcb0dcccf0fe450a3'
  username: 'postmaster@sandbox2bce1d2550dd4a858452a68a5269f473.mailgun.org'
  password: '9c1fb562437e29b8e64b7a96d5177ae1'
